const {esc,clean}=require('./content.cjs');
const fs=require('node:fs');
const site='Travel Vacation Adventure';
const base=(process.env.SITE_URL||'https://travelvacationsadventure-1ec6d.web.app').replace(/\/$/,'');
const link=p=>'/blog/'+p.slug;
const absolute=u=>new URL(u||'/images/coast.jpg',base).href;
function card(p){return `<article class="card"><a href="${link(p)}"><div class="card-image"><img src="${esc(p.image||'/images/coast.jpg')}" alt="${esc(p.imageAlt)}" width="900" height="600" loading="lazy"><span class="card-category">${esc(p.category||'Travel')}</span></div><div class="card-content"><div class="card-meta">${esc(p.date)} · ${Math.max(1,Math.ceil(p.content.replace(/<[^>]*>/g,' ').split(/\s+/).length/220))} min read</div><h3>${esc(p.title)}</h3></div></a><p>${esc(p.description)}</p><a class="read" href="${link(p)}">Read story ↗</a></article>`;}
function layout(title,description,path,body,p){const url=base+path;const img=absolute(p?.image);const schema=p?{'@context':'https://schema.org','@type':'BlogPosting',headline:p.title,description,datePublished:p.date,dateModified:p.updatedAt,image:img,mainEntityOfPage:url,author:{'@type':'Person',name:p.author||site},publisher:{'@type':'Organization',name:site}}:{'@context':'https://schema.org','@type':'Blog',name:site,url};return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | ${site}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(url)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(url)}"><meta property="og:type" content="${p?'article':'website'}"><meta property="og:image" content="${esc(img)}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body><header class="site-header"><div class="wrap header-inner"><a class="brand" href="/"><span class="brand-mark">T</span><span class="brand-name">TRAVEL<small>VACATION ADVENTURE</small></span></a><nav aria-label="Main navigation"><a href="/">Home</a> &nbsp; <a href="/blog/">Journal</a> &nbsp; <a href="/about.html">About</a></nav></div></header><main class="wrap blog-section">${body}</main><footer class="site-footer"><div class="wrap">© ${new Date().getFullYear()} ${site} &nbsp; <a href="/blog/">Journal</a> · <a href="/sitemap.xml">Sitemap</a></div></footer></body></html>`;}
function article(p,posts){return layout(p.seoTitle||p.title,p.seoDescription||p.description,link(p),`<nav class="breadcrumb"><a href="/">Home</a> / <a href="/blog/">Journal</a></nav><header class="article-heading"><p class="eyebrow">${esc(p.category||'Travel')}</p><h1>${esc(p.title)}</h1><p class="dek">${esc(p.description)}</p><div class="card-meta">By ${esc(p.author||site)} · <time datetime="${esc(p.date)}">${esc(p.date)}</time></div></header>${p.image?`<img class="article-cover" src="${esc(p.image)}" alt="${esc(p.imageAlt)}" width="1600" height="900">`:''}<article class="article-body" style="max-width:780px;margin:40px auto">${clean(p.content)}</article><section class="related"><h2>Continue exploring</h2><div class="cards">${posts.filter(x=>x.slug!==p.slug).slice(0,3).map(card).join('')}</div></section>`,p);}
function listing(posts,search='',category=''){const filtered=posts.filter(p=>(!category||p.category===category)&&(!search||`${p.title} ${p.description} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(search.toLowerCase())));return layout('The Sri Lanka journal','Sri Lanka travel guides, thoughtful routes and practical planning ideas.','/blog/',`<header class="page-heading"><p class="eyebrow">Stories for the curious</p><h1>The Sri Lanka journal</h1><p>Places to pause. Stories to inspire your next adventure.</p></header><form action="/blog/" style="display:flex;gap:12px;flex-wrap:wrap;margin:24px 0"><input aria-label="Search stories" name="q" placeholder="Search stories…" value="${esc(search)}" style="padding:12px"><select aria-label="Category" name="category" style="padding:12px"><option value="">All categories</option>${[...new Set(posts.map(p=>p.category).filter(Boolean))].map(c=>`<option ${c===category?'selected':''}>${esc(c)}</option>`).join('')}</select><button class="btn" type="submit">Search</button></form><p>${filtered.length} stories</p><div class="cards">${filtered.map(card).join('')||'<p>No stories found. Try a different search.</p>'}</div>`);}
function home(posts){return fs.readFileSync(__dirname+'/home.html','utf8').replaceAll('https://travelvacationsadventure.github.io/srilanka/',base+'/').replaceAll('G-798Z595DQE','G-RS0LR52536').replace(/<div class="cards">[\s\S]*?<\/div>\s*<\/section>/,`<div class="cards">${posts.slice(0,3).map(card).join('')}</div></section>`);}
function sitemap(posts){return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/','/about.html','/blog/',...posts.map(link)].map(path=>`<url><loc>${esc(base+path)}</loc></url>`).join('')+'</urlset>';}
module.exports={article,listing,home,sitemap,base,layout};
