const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {createRequire}=require('node:module');
const {validate,clean}=require('../functions/content.cjs');const render=require('../functions/render.cjs');
const sample={title:'A thoughtful journey through Sri Lanka',slug:'test-story',description:'A practical introduction to this trip.',category:'Travel',author:'Editor',date:'2026-01-01',image:'/images/coast.jpg',imageAlt:'Palm-lined coast',content:'<h2>Plan your trip</h2><p>A wonderful journey.</p>',status:'published',revision:0};
test('sanitization removes scripts, event handlers and unsafe URLs',()=>{const s=clean('<script>alert(1)</script><img src="x" onerror="x()"><a href="javascript:alert(1)">link</a><h2>Safe</h2>');assert(!s.includes('<script'));assert(!s.includes('onerror'));assert(!s.includes('javascript:'));assert(s.includes('<h2>Safe</h2>'));});
test('validation rejects invalid slugs and incomplete published posts',()=>{assert.throws(()=>validate({...sample,slug:'../escape'}));assert.throws(()=>validate({...sample,description:''}));assert.throws(()=>validate({...sample,image:'javascript:alert(1)'}));assert.throws(()=>validate({...sample,imageAlt:''}));assert.equal(validate(sample).slug,'test-story');});
test('SSR emits complete content, escaped metadata and structured data',()=>{const html=render.article({...sample,title:'A <script> title',updatedAt:'2026-01-01T00:00:00Z'},[]);assert(html.includes('A wonderful journey.'));assert(html.includes('A &lt;script&gt; title'));assert(html.includes('application/ld+json'));assert(html.includes('rel="canonical"'));assert(!html.includes('A <script> title'));});
function backend(){let state=null;const snapshot=v=>({exists:()=>v!==null,val:()=>structuredClone(v)});const root={async get(){return snapshot(state);},async transaction(fn){const next=fn(structuredClone(state));if(next===undefined)return{committed:false};state=next;return{committed:true,snapshot:snapshot(state)};},child(path){const slug=path.split('/')[1];return{async transaction(fn){const next=fn(state.posts?.[slug]||null);if(next===undefined)return{committed:false};if(next===null)delete state.posts[slug];else(state.posts??={})[slug]=next;return{committed:true,snapshot:snapshot(next)};}};}};const realRequire=createRequire(require.resolve('../functions/index.cjs'));const context={exports:{},console,require:name=>({'firebase-functions/v2/https':{onRequest:(_,fn)=>fn},'firebase-admin/app':{initializeApp:()=>{}},'firebase-admin/database':{getDatabase:()=>({ref:()=>root})},'firebase-admin/auth':{getAuth:()=>({verifyIdToken:async token=>{if(token==='bad')throw Error('invalid');return{admin:token==='admin'};}})}}[name]||realRequire(name))};vm.runInNewContext(fs.readFileSync(require.resolve('../functions/index.cjs'),'utf8'),context);return async(path,method='GET',body={},token='admin')=>{const res={code:200,set(){return this;},status(s){this.code=s;return this;},type(){return this;},json(data){this.body=data;return this;},send(data){this.body=data;return this;},redirect(code,to){this.code=code;this.body=to;return this;}};await context.exports.journal({path,method,body,query:{},headers:{authorization:'Bearer '+token}},res);return res;};}
test('authentication and admin access are enforced on server',async()=>{const call=backend();assert.equal((await call('/api/posts','GET',{},'bad')).code,401);assert.equal((await call('/api/posts','GET',{},'regular-user')).code,403);assert.equal((await call('/api/posts')).body.posts.length,12);});
test('create, conflict, edit, draft privacy and deletion lifecycle',async()=>{const call=backend();const create=await call('/api/posts','PUT',sample);assert.equal(create.code,200);assert.equal(create.body.post.revision,1);assert.equal((await call('/api/posts','PUT',sample)).code,409);assert((await call('/blog/test-story')).body.includes('A wonderful journey.'));assert.equal((await call('/blog/test-story.html')).code,301);assert((await call('/sitemap.xml')).body.includes('/blog/test-story'));const draft=await call('/api/posts','PUT',{...sample,revision:1,status:'draft'});assert.equal(draft.body.post.revision,2);assert.equal((await call('/blog/test-story')).code,404);assert(!(await call('/sitemap.xml')).body.includes('/blog/test-story'));assert(!(await call('/')).body.includes('A thoughtful journey through Sri Lanka'));assert.equal((await call('/api/posts/test-story','DELETE',{revision:1})).code,409);assert.equal((await call('/api/posts/test-story','DELETE',{revision:2})).code,200);assert.equal((await call('/api/posts')).body.posts.length,12);});
test('deleting a migrated post never resurrects it from the seed',async()=>{const call=backend();const p=(await call('/api/posts')).body.posts[0];assert.equal((await call('/api/posts/'+p.slug,'DELETE',{revision:1})).code,200);assert.equal((await call('/api/posts')).body.posts.length,11);assert.equal((await call('/blog/'+p.slug)).code,404);});
