import {auth,storage} from './firebase.js';
import {onAuthStateChanged,signInWithEmailAndPassword,signOut,sendPasswordResetEmail,setPersistence,browserSessionPersistence} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {ref,uploadBytesResumable,getDownloadURL} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-storage.js';
const $=id=>document.getElementById(id),fields=['title','slug','description','category','author','date','image','imageAlt','seoTitle','seoDescription'];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let posts=[],filter='all',current=null,dirty=false,busy=false,uploading=false,uploadTarget='cover',slugTouched=false,sessionNumber=0,toastTimer;
function toast(message,error=false){$('toast').textContent=message;$('toast').className=error?'error':'';$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,error?9000:4500);}
function friendly(e){return ({'auth/invalid-credential':'Email or password is incorrect.','auth/invalid-email':'Enter a valid email address.','auth/too-many-requests':'Too many attempts. Please try again later.','auth/network-request-failed':'Check your internet connection and try again.','auth/operation-not-allowed':'Enable Email/Password in Firebase Authentication.','storage/unauthorized':'Image upload was denied. Check the admin claim and deployed Storage rules.'})[e.code]||e.message||'Something went wrong. Please try again.';}
async function api(path='',method='GET',body){const token=await auth.currentUser.getIdToken();const response=await fetch('/api/posts'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json().catch(()=>({error:'Server unavailable. Check your Functions and Hosting deployment.'}));if(!response.ok)throw Error(result.error||'Request failed');return result;}
$('login-form').onsubmit=async e=>{e.preventDefault();$('signin').disabled=true;$('login-message').textContent='Signing in…';try{await setPersistence(auth,browserSessionPersistence);await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('password').value='';}catch(e){$('login-message').textContent=friendly(e);}finally{$('signin').disabled=false;}};
$('reset').onclick=async()=>{if(!$('email').validity.valid||!$('email').value){$('login-message').textContent='Enter your email address first.';return;}try{await sendPasswordResetEmail(auth,$('email').value.trim());$('login-message').textContent='If that account exists, a password reset email is on its way.';}catch(e){$('login-message').textContent=friendly(e);}};
onAuthStateChanged(auth,async user=>{const session=++sessionNumber;$('login').hidden=!!user;$('app').hidden=!user;if(!user){posts=[];current=null;dirty=false;$('content').innerHTML='';$('post-form').reset();$('post-list').innerHTML='';$('library').hidden=false;$('editor-view').hidden=true;return;}$('account-email').textContent=user.email;try{const token=await user.getIdTokenResult(true);if(!token.claims.admin)throw Error('Complete the one-time admin setup for this email, then sign in again.');await load();}catch(e){if(session!==sessionNumber)return;await signOut(auth);$('login-message').textContent=friendly(e);}});
$('logout').onclick=async()=>{if(canLeave())await signOut(auth);};
async function load(){const result=await api();posts=result.posts.sort((a,b)=>b.date.localeCompare(a.date));draw();}
function draw(){const q=$('search').value.toLowerCase(),cat=$('category-filter').value;const categories=[...new Set(posts.map(p=>p.category).filter(Boolean))].sort();$('category-filter').innerHTML='<option value="">All categories</option>'+categories.map(c=>`<option ${c===cat?'selected':''}>${esc(c)}</option>`).join('');$('categories').innerHTML=categories.map(c=>`<option value="${esc(c)}">`).join('');$('total').textContent=posts.length;$('nav-count').textContent=posts.length;$('published').textContent=posts.filter(p=>p.status==='published').length;$('drafts').textContent=posts.filter(p=>p.status==='draft').length;const result=posts.filter(p=>(filter==='all'||p.status===filter)&&(!cat||p.category===cat)&&`${p.title} ${p.author} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q));$('post-list').innerHTML=result.map(p=>`<tr><td><div class="story-cell"><img src="${esc(p.image||'/images/coast.jpg')}" alt="" loading="lazy"><div><b>${esc(p.title)}</b><small>${esc(p.category||'Uncategorized')} · ${esc(p.author)}</small></div></div></td><td><span class="badge ${p.status}">${p.status==='published'?'● Published':'◌ Draft'}</span></td><td>${esc(p.date)}</td><td><div class="row-actions"><button data-edit="${p.slug}" aria-label="Edit ${esc(p.title)}">Edit</button>${p.status==='published'?`<a href="/blog/${p.slug}" target="_blank" rel="noopener" aria-label="View story">↗</a>`:''}<button class="delete" data-delete="${p.slug}" aria-label="Delete ${esc(p.title)}">×</button></div></td></tr>`).join('');$('empty').hidden=!!result.length;$('result-count').textContent=`Showing ${result.length} of ${posts.length} stories`;}
$('search').oninput=draw;$('category-filter').onchange=draw;
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));draw();});
$('refresh').onclick=async()=>{try{await load();toast('Journal refreshed.');}catch(e){toast(friendly(e),true);}};
$('post-list').onclick=async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)open(posts.find(p=>p.slug===edit.dataset.edit));if(del){const p=posts.find(p=>p.slug===del.dataset.delete);if(!confirm(`Delete “${p.title}”? This cannot be undone. Uploaded images remain available for other posts.`))return;del.disabled=true;try{await api('/'+p.slug,'DELETE',{revision:p.revision});await load();toast('Story deleted.');}catch(e){toast(friendly(e),true);}finally{del.disabled=false;}}};
function canLeave(){if(busy||uploading){toast('Wait for the current save or upload to finish.',true);return false;}return !dirty||confirm('Leave this story and discard unsaved changes?');}
function library(){if(!canLeave())return;dirty=false;$('library').hidden=false;$('editor-view').hidden=true;$('breadcrumb').textContent='All stories';}
$('back').onclick=library;$('nav-posts').onclick=library;
function open(p=null){if(!canLeave())return;current=p?structuredClone(p):null;slugTouched=!!p;const defaults={author:'Travel Vacation Adventure',date:new Date().toISOString().slice(0,10)};for(const id of fields)$(id).value=p?.[id]||defaults[id]||'';$('content').innerHTML=p?.content||'';$('tags').value=(p?.tags||[]).join(', ');$('slug').readOnly=!!p;$('editor-heading').textContent=p?'Refine your story.':'A new story begins.';$('save-state').textContent=p?`${p.status==='published'?'Published':'Draft'} · Last saved ${new Date(p.updatedAt).toLocaleString()}`:'Unsaved story';$('publish').textContent=p?.status==='published'?'Update live story ↗':'Publish story ↗';$('save-draft').textContent=p?.status==='published'?'Unpublish to draft':'Save draft';$('library').hidden=true;$('editor-view').hidden=false;$('breadcrumb').textContent=p?'Edit story':'New story';dirty=false;updatePreview();window.scrollTo(0,0);}
for(const id of ['new-post','nav-new'])$(id).onclick=()=>open();
const slugify=s=>s.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,180).replace(/-$/,'');
$('title').addEventListener('input',()=>{if(!slugTouched&&!current)$('slug').value=slugify($('title').value);});$('slug').addEventListener('input',()=>slugTouched=true);
function changed(){dirty=true;$('save-state').textContent='Unsaved changes';updatePreview();}
$('post-form').addEventListener('input',changed);$('post-form').onsubmit=e=>e.preventDefault();
function updatePreview(){const text=$('content').textContent.trim(),words=text?text.split(/\s+/).length:0;const title=$('seoTitle').value||$('title').value,description=$('seoDescription').value||$('description').value;$('word-count').textContent=`${words} words · ${Math.max(1,Math.ceil(words/220))} min read`;$('seo-url').textContent=location.origin+'/blog/'+($('slug').value||'your-story');$('seo-preview-title').textContent=title||'Your story title';$('seo-preview-description').textContent=description||'Your description will appear here.';$('seo-title-count').textContent=`(${title.length} characters · aim for 30–60)`;$('seo-description-count').textContent=`(${description.length} characters · aim for 120–160)`;$('seo-checks').innerHTML=[[title.length>=30&&title.length<=60,'Descriptive search title (30–60 characters)'],[description.length>=120&&description.length<=160,'Helpful meta description (120–160 characters)'],[!!$('content').querySelector('h2'),'Clear section headings'],[!$('image').value||!!$('imageAlt').value,'Cover image has descriptive alt text']].map(([ok,t])=>`<li>${ok?'✓':'○'} ${t}</li>`).join('');const src=$('image').value.trim();$('cover-preview').hidden=!src;$('cover-placeholder').hidden=!!src;if(src&&(/^(https:\/\/|\/[^/])/.test(src)))$('cover-preview').src=src;else $('cover-preview').removeAttribute('src');}
$('content').addEventListener('paste',e=>{e.preventDefault();document.execCommand('insertText',false,e.clipboardData.getData('text/plain'));changed();});
document.querySelectorAll('[data-command],[data-block]').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>{$('content').focus();document.execCommand(b.dataset.command||'formatBlock',false,b.dataset.block||null);changed();};});
$('add-link').onmousedown=e=>e.preventDefault();$('add-link').onclick=()=>{const url=prompt('Link address (https://…)');if(!url)return;if(!/^https:\/\//i.test(url)){toast('Use a complete HTTPS link.',true);return;}$('content').focus();document.execCommand('createLink',false,url);changed();};
function setBusy(value){busy=value;$('post-form').inert=value;for(const id of ['save-draft','publish','preview'])$(id).disabled=value;}
async function save(status){if(busy||uploading)return;if(!$('post-form').reportValidity())return;if(current?.status==='published'&&status==='draft'&&!confirm('Unpublish this article? It will no longer be visible on the website.'))return;const payload=Object.fromEntries(fields.map(id=>[id,$(id).value.trim()]));Object.assign(payload,{content:$('content').innerHTML,tags:$('tags').value.split(',').map(x=>x.trim()).filter(Boolean),status,revision:current?.revision||0});setBusy(true);try{const result=await api('','PUT',payload);current=result.post;dirty=false;setBusy(false);open(current);posts=posts.filter(p=>p.slug!==current.slug);posts.unshift(current);draw();toast(status==='published'?'Story published. Your website is up to date.':'Draft saved.');}catch(e){toast(friendly(e),true);}finally{setBusy(false);}}
$('save-draft').onclick=()=>save('draft');$('publish').onclick=()=>save('published');
$('upload-cover').onclick=()=>{uploadTarget='cover';$('file').click();};$('inline-image').onclick=()=>{uploadTarget='inline';$('file').click();};
$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;$('file').value='';if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>=10*1024*1024){toast('Choose a JPG, PNG, WebP or GIF smaller than 10 MB.',true);return;}let alt='';if(uploadTarget==='inline'){alt=prompt('Describe this image (alt text):')||'';if(!alt.trim())return;}uploading=true;$('upload-progress').hidden=false;for(const id of ['upload-cover','inline-image','save-draft','publish'])$(id).disabled=true;try{const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'}[file.type];const task=uploadBytesResumable(ref(storage,'blog-images/'+crypto.randomUUID()+'.'+ext),file,{contentType:file.type});await new Promise((resolve,reject)=>task.on('state_changed',s=>$('upload-progress').value=s.bytesTransferred/s.totalBytes*100,reject,resolve));const url=await getDownloadURL(task.snapshot.ref);if(uploadTarget==='cover'){$('image').value=url;if(!$('imageAlt').value)$('imageAlt').focus();}else{const p=document.createElement('p'),img=document.createElement('img');img.src=url;img.alt=alt;img.loading='lazy';p.append(img);$('content').append(p);}changed();toast('Image uploaded. Save the story to apply it.');}catch(e){toast(friendly(e),true);}finally{uploading=false;$('upload-progress').hidden=true;for(const id of ['upload-cover','inline-image','save-draft','publish'])$(id).disabled=false;}};
$('remove-cover').onclick=()=>{$('image').value='';$('imageAlt').value='';changed();};
$('preview').onclick=()=>{const css='<style>body{font:17px/1.8 Georgia;color:#233d32;max-width:780px;margin:50px auto;padding:0 25px}h1{font-size:42px;line-height:1.2}h2{line-height:1.3}img{max-width:100%;height:auto}blockquote{border-left:3px solid #c0cda8;padding-left:20px}small{font:12px sans-serif;color:#758372}</style>';$('preview-frame').srcdoc=`<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src https: ${location.origin}; style-src 'unsafe-inline';"><title>Preview</title>${css}</head><body><small>${esc($('category').value)} · ${esc($('date').value)}</small><h1>${esc($('title').value||'Untitled story')}</h1><p>${esc($('description').value)}</p>${$('image').value?`<img src="${esc($('image').value)}" alt="${esc($('imageAlt').value)}">`:''}${$('content').innerHTML}</body></html>`;$('preview-dialog').showModal();};$('close-preview').onclick=()=>$('preview-dialog').close();
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),posts},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='travel-journal-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('beforeunload',e=>{if(dirty||busy||uploading){e.preventDefault();e.returnValue='';}});
